version: '3.7'

networks:
  eveve:

volumes:
  node_modules:

services:
  frontend:
    container_name: frontend
    build:
      context: ./
      dockerfile: Dockerfile
    image: eveve/react-test:dev
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
    ports:
      - '3000:3000'
    networks:
      - eveve
    environment:
      - NODE_ENV=development
